# Loader metadata
modLoader = "javafml"
loaderVersion = "[47,)"
license = "BSD 3"

# TFC Florae
[[mods]]
    modId = "tfcflorae"
    version = "${file.jarVersion}"
    displayName = "TFC Florae"
    credits = "By Verph and with help from Loevendallund, Blade67, SeriousCreeper and many more. Huge thanks and credits to cubey79 for allowing the usage of certain wood textures from their resource pack Vanilla Themed TFC+ & TFC TNG goes towards facetorched and yeahminecraft16 for allowing me to make use of many of their plant assets from TFC+ Aesthetics!"
    authors = "Verph"
    description = '''TFC Florae - A large and environmentally impactful addon for TerraFirmaCraft'''

# Dependencies
[[dependencies.tfcflorae]]
	modId = "tfc"
	mandatory = true
	versionRange = "[1.20.1-3.2.10,)"
	side = "BOTH"
	ordering = "AFTER"

[[dependencies.tfcflorae]]
	modId = "forge"
	mandatory = true
	versionRange = "[47,)"
	side = "BOTH"
	ordering = "AFTER"

[[dependencies.tfcflorae]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.20.1,)"
	side = "BOTH"
	ordering = "AFTER"
