license = "BSD 3" 
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
modLoader = "javafml" #mandatory
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId = "tfcflorae" #mandatory
version = "${file.jarVersion}" #mandatory
# A display name for the mod
displayName = "TFCFlorae" #mandatory
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile = "logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "Verph, Loevendallund" #optional
description = '''
An addon for TFC.
''' 
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tfcflorae]]
modId = "tfc"
mandatory = true
versionRange = "[1.18.2-2.0.34,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfcflorae]] #optional
mandatory = true #mandatory
modId = "forge" #mandatory
versionRange = "[40,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "AFTER"
side = "BOTH"

# Here's another dependency
[[dependencies.tfcflorae]]
mandatory = true
modId = "minecraft"
ordering = "AFTER"
side = "BOTH"
versionRange = "[1.18.2,1.19)"
